-- HEADER-START
-- DESCRIPTION This is the oracle customisation data definition script generated on 2016-06-19 19:40:22
--  Note that this script has DROP dtatements that may generate errors when the script is first run -
--  these can be ignored.
-- PARAMETER schema
-- DESCRIPTION Specify the database schema where these tables will be created.
-- DEFAULT [TRADEIN1]
-- VALUE ${schema}
--
-- HEADER-END
INSERT INTO ${schema}.CHPFLOG ( TIMESEQ, DBVERSION, SOURCE, ACTION, COMMENTS ) VALUES ( TO_CHAR ( SYSDATE, 'YYYY/MM/DD-HH24:MI:SS' ), 'CUSTOM', 'post_install.sql', 'Starting Custom Copy', 'Executing copy script for extra customisation tables'  );

INSERT INTO ${schema}.EXTPMAPI ("GZSEQ", "GZWSID")
SELECT "GZSEQ", "GZWSID" FROM ${schema}.EXTPMAPI_BACKUP;

INSERT INTO ${schema}.EXTEVENT ("KEY29", "TYPEFLAG", "TSTAMP", "INITED", "EVENT", "APP_USR", "APRV_NUM", "LOS_NMBR", "CHANNEL", "PRIORITY", "BENFTYPE", "CUATDEBC", "RESN_CNC", "CASH_COL", "LOS_STUS", "TOTINVAM", "CCY_2", "ADVPAYAM", "CCY_1", "DISCAMNT", "CCY", "INVOAMNT", "CCY_3", "BANKOFGR", "GOODCODE", "GOODPROD", "GOODDEST"
--, "COVERID", "LOSPAYAC"
)
SELECT "KEY29", "TYPEFLAG", "TSTAMP", "INITED", "EVENT", "APP_USR", "APRV_NUM", "LOS_NMBR", "CHANNEL", "PRIORITY", "BENFTYPE", "CUATDEBC", "RESN_CNC", "CASH_COL", "LOS_STUS", "TOTINVAM", "CCY_2", "ADVPAYAM", "CCY_1", "DISCAMNT", "CCY", "INVOAMNT", "CCY_3", "BANKOFGR", "GOODCODE", "GOODPROD", "GOODDEST"
--, "COVERID", "LOSPAYAC"
FROM ${schema}.EXTEVENT_BACKUP;

INSERT INTO ${schema}.EXTEVSTEP ("KEY29", "TYPEFLAG", "TSTAMP", "EVENTSTEP", "INITED")
SELECT "KEY29", "TYPEFLAG", "TSTAMP", "EVENTSTEP", "INITED" FROM ${schema}.EXTEVSTEP_BACKUP;

INSERT INTO ${schema}.EXTMASTER ("KEY29", "TYPEFLAG", "TSTAMP", "INITED", "MASTER", "APP_USR", "APRV_NUM", "LOS_NMBR", "BENFTYPE", "RESN_CNC", "LOS_STUS", "CUATDEBC", "CASH_COL", "CHANNEL", "PRIORITY", "GOODCODE", "DISCAMNT", "CCY", "ADVPAYAM", "CCY_1", "TOTINVAM", "CCY_2", "BANKOFGR", "INVOAMNT", "CCY_3", "GOODPROD", "GOODDEST"
--, "LOSPAYAC"
)
SELECT "KEY29", "TYPEFLAG", "TSTAMP", "INITED", "MASTER", "APP_USR", "APRV_NUM", "LOS_NMBR", "BENFTYPE", "RESN_CNC", "LOS_STUS", "CUATDEBC", "CASH_COL", "CHANNEL", "PRIORITY", "GOODCODE", "DISCAMNT", "CCY", "ADVPAYAM", "CCY_1", "TOTINVAM", "CCY_2", "BANKOFGR", "INVOAMNT", "CCY_3", "GOODPROD", "GOODDEST"
--, "LOSPAYAC" 
FROM ${schema}.EXTMASTER_BACKUP;

INSERT INTO ${schema}.EXTMSS ("KEY29", "TYPEFLAG", "TSTAMP", "INITED", "MASTER", "APP_USR", "APRV_NUM", "LOS_NMBR", "BENFTYPE", "RESN_CNC", "LOS_STUS", "CUATDEBC", "CASH_COL", "CHANNEL", "PRIORITY", "GOODCODE", "DISCAMNT", "CCY", "ADVPAYAM", "CCY_1", "TOTINVAM", "CCY_2", "BANKOFGR", "INVOAMNT", "CCY_3", "GOODPROD", "GOODDEST"
--, "LOSPAYAC"
)
SELECT "KEY29", "TYPEFLAG", "TSTAMP", "INITED", "MASTER", "APP_USR", "APRV_NUM", "LOS_NMBR", "BENFTYPE", "RESN_CNC", "LOS_STUS", "CUATDEBC", "CASH_COL", "CHANNEL", "PRIORITY", "GOODCODE", "DISCAMNT", "CCY", "ADVPAYAM", "CCY_1", "TOTINVAM", "CCY_2", "BANKOFGR", "INVOAMNT", "CCY_3", "GOODPROD", "GOODDEST"
--, "LOSPAYAC" 
FROM ${schema}.EXTMSS_BACKUP;

INSERT INTO ${schema}.EXTPOSTING ("KEY29", "TYPEFLAG", "TSTAMP", "FAPOST", "INITED", "POSTTYPE", "PCAPOST", "POST", "EVENT", "MASTER")
SELECT "KEY29", "TYPEFLAG", "TSTAMP", "FAPOST", "INITED", "POSTTYPE", "PCAPOST", "POST", "EVENT", "MASTER" FROM ${schema}.EXTPOSTING_BACKUP;

INSERT INTO ${schema}.EXTCUST ("CUST_SBB", "CUST", "INITED", "GRTAXNUM", "TAXOFFID", "DESTAXOF", "LEGEXDAT", "PDTAXEXD", "APRVLUNT", "LEGALEXP", "PDTAXEXP", "CPRCSDAT", "CUSTFNGR", "CUSTFNLA", "ACOFNAME", "TAXOFFAD")
SELECT "CUST_SBB", "CUST", "INITED", "GRTAXNUM", "TAXOFFID", "DESTAXOF", "LEGEXDAT", "PDTAXEXD", "APRVLUNT", "LEGALEXP", "PDTAXEXP", "CPRCSDAT", "CUSTFNGR", "CUSTFNLA", "ACOFNAME", "TAXOFFAD" FROM ${schema}.EXTCUST_BACKUP;

INSERT INTO ${schema}.EXTICUST ("KEY29", "TYPEFLAG", "TSTAMP", "INITED", "TICUST")
SELECT "KEY29", "TYPEFLAG", "TSTAMP", "INITED", "TICUST" FROM ${schema}.EXTICUST_BACKUP;

INSERT INTO ${schema}.PIRCRS ("CRS")
SELECT "CRS" FROM ${schema}.PIRCRS_BACKUP;

INSERT INTO ${schema}.CHPFLOG ( TIMESEQ, DBVERSION, SOURCE, ACTION, COMMENTS ) VALUES ( TO_CHAR ( SYSDATE+ 1, 'YYYY/MM/DD-HH24:MI:SS' ), 'CUSTOM' , 'post_install.sql' , 'Custom Copy Complete', 'Completed copy script for extra customisation tables');

COMMIT;
